GET http://localhost:3000
Accept: application/json

###
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "Kau Terindah",
  "year": 2020,
  "performer": "Erik",
  "genre": "Indie",
  "duration": 120
}

###
GET http://localhost:3000/songs
Accept: application/json
