package main

import (
	"fmt"
	swagger "github.com/arsmn/fiber-swagger/v2"
	"github.com/erikrios/open-music-api-go-language/src/api/home"
	"github.com/gofiber/fiber/v2"
	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/erikrios/open-music-api-go-language/docs"
)

// @title Open Music API
// @version 1.0
// @description The API of Open Music.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /
// @query.collection.format multi
// @schemes http

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

func main() {
	app := fiber.New()

	app.Get("/swagger/*", swagger.Handler)

	home.HomeRoutes(app)

	if err := app.Listen(":3000"); err != nil {
		fmt.Println("Failed to start the server:", err)
	} else {
		fmt.Println("Server starting on port", 3000)
	}
}
